name: YiXu-CookingSystem
version: '1.0'
main: com.yixu.CookingSystem
api-version: '1.21'
softdepend:
  - DecentHolograms
  - ItemsAdder

depend:
  - CustomCrops

commands:
  yixu-cookingsystem:
    description: 插件主命令
    usage: /yixu-cookingsystem <reload>

permissions:
  yixu-cookingsystem.reload:
    description: 重载烹饪系统配置文件
    default: op